; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mzeroUSB]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>

[env:radio_send_test]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>

[env:sensor_radio_test]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>

[env:mpu6050_test]
platform = atmelsam
board = mzeroUSB
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
framework = arduino
lib_deps = Wire

[env:flight_computer]
platform = atmelsam
board = mzeroUSB
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
framework = arduino
lib_deps = Wire
