; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mzeroUSB]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
lib_deps = 
	arduino-libraries/SD@^1.3.0
	sandeepmistry/LoRa@^0.8.0

[env:radio_send_test]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
lib_deps = 
	arduino-libraries/SD@^1.3.0
	sandeepmistry/LoRa@^0.8.0

[env:sensor_radio_test]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
lib_deps = 
	arduino-libraries/SD@^1.3.0
	sandeepmistry/LoRa@^0.8.0

[env:mpu6050_test]
platform = atmelsam
board = mzeroUSB
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
framework = arduino
lib_deps = 
	Wire
	arduino-libraries/SD@^1.3.0
	sandeepmistry/LoRa@^0.8.0

[env:flight_computer]
platform = atmelsam
board = mzeroUSB
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
framework = arduino
lib_deps = 
	Wire
	arduino-libraries/SD@^1.3.0
	ress997/TinyGPSPlusPlus@^0.0.4
	sandeepmistry/LoRa@^0.8.0

[env:radio_batch_send]
platform = atmelsam
board = mzeroUSB
framework = arduino
build_src_filter = +<*.h> +<main_${PIOENV}.cpp>
lib_deps = 
	arduino-libraries/SD@^1.3.0
	sandeepmistry/LoRa@^0.8.0
